services:
  psql:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - data:/var/lib/postgresql/data 
    ports:
      - ${POSTGRES_PORT}:5432
 
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
 
volumes:
  data: